runtime: python38

entrypoint: gunicorn -b :$PORT twitchrss:app

env_variables:
  TWITCH_CLIENT_ID: __INSERT_TWITCH_CLIENT_ID_HERE__

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /
  static_files: index.html
  upload: index\.html

- url: /.+
  script: auto

automatic_scaling:
  max_instances: 1
